### ISSUE TITLE
Problems with Scanner and syslog lines without \n

### ISSUE THREAD

**Issue by middelink** [mcuadros/go-syslog#10]
The use of a bufio.Scanner assumes (by default) syslog messages end in a \n. This is often not the case, Esp. on UDP, 1 datagram == 1 syslog frame and the message part is allowed to fill the rest of the packet.

Also http://www.ietf.org/rfc/rfc3164.txt $4.1.3 clearly states the MSG part has no ending delimiter.

**Comment by abligh** [comment]
See also #15 - I think on UDP we shouldn't be using a split function at all. The end of the packet is the delimiter.

**Comment by abligh** [comment]
This pull request *may* fix this: https://github.com/abligh/go-syslog/commit/df573444e870c589591445efd55b4c953580a83f
