### ISSUE TITLE
error detection and concurrency

### ISSUE THREAD

**Issue by dan-frohlich** [mcuadros/go-syslog#28]
server.go parse looks something like this...

```
func (s *Server) parser(line []byte, client string, tlsPeer string) {
	parser := s.format.GetParser(line)
	err := parser.Parse()
	if err != nil {
		s.lastError = err
	}

	logParts := parser.Dump()
	logParts["client"] = client
	logParts["tls_peer"] = tlsPeer

	s.handler.Handle(logParts, int64(len(line)), err)
}

```

as a consumer of logparts there is no obvious way to tell if there was an error or if the last error is in fact the error caused by the logpart I am processing.

scenario:

1. message "A" arrives and generates an error say "GENERIC_ERROR_A"
2. server.go parse 
2.1. copies "GENERIC_ERROR_A" to last error 
2.2. Dumps the logParts (zeroed structs?) and passes it to s.handler
3. s.handler is (my) channel handler, writing to (my) channel which my code is consuming on a separate go routine.
4. message "B" arrives and generates an error say "GENERIC_ERROR_B"
5. server.go parse 
5.1. copies "GENERIC_ERROR_B" to last error 
5.2. Dumps the logParts (zeroed structs?) and passes it to s.handler

now say steps 4, 5 and 5.1 execute before I process the logparts for message a...

There is no clear way to distinguish if parsing a given message generated a specific error.

I have no way to get the error associated with message A as it has been overwritten.
 
I would propose that an parse_error or error field be added to the Logparts inorder to communicate specific error occurrences back to the the called.

Alternately a second handler method to handles errors could be added. In this case messages which generated an error should result in the error handler being called and NOT the LogParts handler.

It would also be nice for troubleshooting purposes to have a reference to the original message that generated the error.

**Comment by mcuadros** [comment]
Since `syslog.Handler` is a interface:

```go
//The handler receive every syslog entry at Handle method
type Handler interface {
	Handle(syslogparser.LogParts, int64, error)
}
```

You can create your custom handler sending to you a struct with the two needed values (the `LogParts` and the error) 

BTW A PR is more than welcome.
