### ISSUE TITLE
It's not possible to implement custom Format since syslogparser was integrated

### ISSUE THREAD

**Issue by cezarsa** [mcuadros/go-syslog#30]
Although there is a `Format` interface, the signature of `GetParser` is using an internal package:
```go
type Format interface {
	GetParser([]byte) syslogparser.LogParser
	GetSplitFunc() bufio.SplitFunc
}
```
This way it's not possible to write a custom Format because it's impossible to import the internal package `syslogparser.LogParser`.

My suggestion is that `GetParser` should return `Parser` interface with methods `Parse()` and `Dump()`.

I can work on a PR later if this change is something you're okay with.

**Comment by mcuadros** [comment]
Sure, go ahead, thanks.
